/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_signup_window (void);
GtkWidget* create_signin_window (void);
GtkWidget* create_admin_window (void);
GtkWidget* create_citizen_window (void);
GtkWidget* create_service_display_dialog (void);
