/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_signup_window (void);
GtkWidget* create_signin_window (void);
GtkWidget* create_admin_window (void);
GtkWidget* create_citizen_window (void);
GtkWidget* create_admin_agent_dialog (void);
GtkWidget* create_admin_service_delete_dialog (void);
GtkWidget* create_admin_service_update_dialog (void);
GtkWidget* create_admin_service_display_dialog (void);
GtkWidget* create_citizen_delete_dialog (void);
